name: ServerGuard
version: 1.0
main: com.tuservidor.serverguard.ServerGuard
api-version: '1.20'
author: TuNombre
description: Protege y gestiona las regiones de tu servidor.
commands:
  region:
    description: Comando principal para gestionar regiones.
    aliases: [rg]
    permission: serverguard.admin