name: StaffTools
version: 1.0
main: com.tuservidor.stafftools.StaffTools
api-version: '1.20'
author: TuNombre
description: Herramientas avanzadas para el equipo de Staff.
commands:
  staff:
    description: Activa o desactiva el modo Staff.
    aliases: [s]
    permission: stafftools.command.mode
  ban:
    description: Banea a un jugador del servidor.
    usage: "/ban <jugador> [tiempo] [razón]"
    permission: stafftools.command.ban
  unban:
    description: Desbanea a un jugador.
    usage: "/unban <jugador>"
    permission: stafftools.command.unban
  kick:
    description: Expulsa a un jugador del servidor.
    usage: "/kick <jugador> [razón]"
    permission: stafftools.command.kick
  mute:
    description: Silencia a un jugador en el chat.
    usage: "/mute <jugador> [tiempo] [razón]"
    permission: stafftools.command.mute
  unmute:
    description: Quita el silencio a un jugador.
    usage: "/unmute <jugador>"
    permission: stafftools.command.unmute